http:
  routers:
    traefik:
      rule: "Host(`traefik.${{REPLACE_UNIFFO_LOCAL_DOMAIN}}`)"
      service: "api@internal"
      entryPoints:
        - "websecure"
tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
