import { CLI_PROJECT_STRUCTURE_ENVIRONMENTS_DIR_BASENAME } from './CLI_PROJECT_STRUCTURE_ENVIRONMENTS_DIR_BASENAME.ts';
import { CLI_PROJECT_STRUCTURE_UNIFFO_DIR_BASENAME } from './CLI_PROJECT_STRUCTURE_UNIFFO_DIR_BASENAME.ts';

export const CLI_PROJECT_STRUCTURE_ENVIRONMENTS_DIR_PATH =
    `${CLI_PROJECT_STRUCTURE_UNIFFO_DIR_BASENAME}/${CLI_PROJECT_STRUCTURE_ENVIRONMENTS_DIR_BASENAME}`;
