// Copyright 2023-2025 Maciej Koralewski. All rights reserved. EULA license.

import { CLI_PROJECT_ENVIRONMENT_STRUCTURE_ROOT_ENV_FILE_BASENAME } from './CLI_PROJECT_ENVIRONMENT_STRUCTURE_ROOT_ENV_FILE_BASENAME.ts';

export const CLI_PROJECT_ENVIRONMENT_STRUCTURE_ROOT_ENV_FILE_PATH =
    `${CLI_PROJECT_ENVIRONMENT_STRUCTURE_ROOT_ENV_FILE_BASENAME}`;
