// Copyright 2023-2024 Maciej Koralewski. All rights reserved. EULA license.

import { CLI_PROJECT_ENVIRONMENT_STRUCTURE_COMPOSE_DIR_BASENAME } from './CLI_PROJECT_ENVIRONMENT_STRUCTURE_COMPOSE_DIR_BASENAME.ts';
import { CLI_PROJECT_ENVIRONMENT_STRUCTURE_ROOT_ENV_FILE_BASENAME } from './CLI_PROJECT_ENVIRONMENT_STRUCTURE_ROOT_ENV_FILE_BASENAME.ts';
import { CLI_PROJECT_STRUCTURE_EMPTY_DIR } from './CLI_PROJECT_STRUCTURE_EMPTY_DIR.ts';
import { CLI_PROJECT_STRUCTURE_EMPTY_FILE } from './CLI_PROJECT_STRUCTURE_EMPTY_FILE.ts';

export const CLI_PROJECT_ENVIRONMENT_STRUCTURE = {
	[CLI_PROJECT_ENVIRONMENT_STRUCTURE_ROOT_ENV_FILE_BASENAME]: CLI_PROJECT_STRUCTURE_EMPTY_FILE,
	[CLI_PROJECT_ENVIRONMENT_STRUCTURE_COMPOSE_DIR_BASENAME]: CLI_PROJECT_STRUCTURE_EMPTY_DIR,
};
