import { CLI_PROJECT_STRUCTURE_SOURCE_DIR_BASENAME } from './CLI_PROJECT_STRUCTURE_SOURCE_DIR_BASENAME.ts';

export const CLI_PROJECT_STRUCTURE_SOURCE_DIR_PATH = `${CLI_PROJECT_STRUCTURE_SOURCE_DIR_BASENAME}`;
