// Copyright 2023-2025 Maciej Koralewski. All rights reserved. EULA license.

import { docker } from '../global/docker.ts';
import { getCurrentCliVersion } from '../utils/get_current_cli_version/get_current_cli_version.ts';
import { CLI_PROJECT_STRUCTURE_EMPTY_DIR } from './CLI_PROJECT_STRUCTURE_EMPTY_DIR.ts';
import { CLI_PROJECT_STRUCTURE_ENVIRONMENTS_DIR_BASENAME } from './CLI_PROJECT_STRUCTURE_ENVIRONMENTS_DIR_BASENAME.ts';
import { CLI_PROJECT_STRUCTURE_ROOT_DOCKER_COMPOSE_FILE_BASENAME } from './CLI_PROJECT_STRUCTURE_ROOT_DOCKER_COMPOSE_FILE_BASENAME.ts';
import { CLI_PROJECT_STRUCTURE_SOURCE_DIR_BASENAME } from './CLI_PROJECT_STRUCTURE_SOURCE_DIR_BASENAME.ts';
import { CLI_PROJECT_STRUCTURE_UNIFFO_DIR_BASENAME } from './CLI_PROJECT_STRUCTURE_UNIFFO_DIR_BASENAME.ts';
import { CLI_PROJECT_STRUCTURE_VERSION_FILE_BASENAME } from './CLI_PROJECT_STRUCTURE_VERSION_FILE_BASENAME.ts';

export const CLI_PROJECT_STRUCTURE = {
	[CLI_PROJECT_STRUCTURE_UNIFFO_DIR_BASENAME]: {
		[CLI_PROJECT_STRUCTURE_ENVIRONMENTS_DIR_BASENAME]: CLI_PROJECT_STRUCTURE_EMPTY_DIR,
		[CLI_PROJECT_STRUCTURE_VERSION_FILE_BASENAME]: getCurrentCliVersion(),
	},
	[CLI_PROJECT_STRUCTURE_SOURCE_DIR_BASENAME]: CLI_PROJECT_STRUCTURE_EMPTY_DIR,
	[CLI_PROJECT_STRUCTURE_ROOT_DOCKER_COMPOSE_FILE_BASENAME]: docker.composeDefinitions().getByName('root').getStructure()[CLI_PROJECT_STRUCTURE_ROOT_DOCKER_COMPOSE_FILE_BASENAME],
};
