// Copyright 2023-2024 Maciej Koralewski. All rights reserved. EULA license.

import { CLI_PROJECT_ENVIRONMENT_STRUCTURE_COMPOSE_DIR_BASENAME } from './CLI_PROJECT_ENVIRONMENT_STRUCTURE_COMPOSE_DIR_BASENAME.ts';

export const CLI_PROJECT_ENVIRONMENT_STRUCTURE_COMPOSE_DIR_PATH =
    `${CLI_PROJECT_ENVIRONMENT_STRUCTURE_COMPOSE_DIR_BASENAME}`;
