global:
  checkNewVersion: true
  sendAnonymousUsage: false
log:
  level: INFO
  format: common
api:
  dashboard: true
  insecure: false
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: "${{REPLACE_UNIFFO_PUBLIC_NETWORK_NAME}}"
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
